# Generated by Django 3.0.11 on 2020-12-25 21:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer', models.CharField(max_length=50)),
                ('village', models.CharField(blank=True, max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=7756)),
                ('mandal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='field.Mandals')),
            ],
        ),
        migrations.CreateModel(
            name='CropDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(choices=[('Rice', 'Rice'), ('Vegetables', 'Vegetables'), ('Cotton', 'Cotton'), ('Maize', 'Maize'), ('Cerials', 'Cerials'), ('Others', 'Others')], max_length=30)),
                ('crop_status', models.CharField(choices=[('seedling', 'Seedling'), ('vegetative', 'Vegetative'), ('budding', 'Budding'), ('flowering', 'Flowering'), ('ripening', 'Ripening'), ('Harvested', 'Harvested')], max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='field.Field', unique_for_month='created_date')),
            ],
        ),
    ]
