# Generated by Django 3.0.11 on 2020-12-25 21:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0002_cropdetail_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop50',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, dim=3, null=True, srid=7756)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('village', models.CharField(blank=True, max_length=150, null=True)),
                ('crop', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'crop50',
                'managed': False,
            },
        ),
    ]
