# Generated by Django 3.0.11 on 2020-12-25 21:53

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0003_crop50'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newcrop50',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=7756)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('village', models.CharField(blank=True, max_length=150, null=True)),
                ('crop', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'newcrop50',
                'managed': False,
            },
        ),
    ]
