# Generated by Django 3.0.11 on 2020-12-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0004_newcrop50'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropdetail',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
