# Generated by Django 3.0.11 on 2020-12-26 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0005_cropdetail_updated_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropNdvi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=3, max_digits=4)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ndvi_values', to='field.CropDetail')),
            ],
        ),
    ]
