# Generated by Django 3.0.11 on 2020-12-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0007_auto_20201227_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropdetail',
            name='crop_type',
            field=models.CharField(choices=[('Rice', 'Rice'), ('Vegetables', 'Vegetables'), ('Cotton', 'Cotton'), ('Maize', 'Maize'), ('Cerials', 'Cerials'), ('Mango', 'Mango'), ('Others', 'Others')], max_length=30),
        ),
    ]
